# Site settings
title: thefron's knowledge base
email: thefron@me.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thefron.github.io" # the base hostname & protocol for your site
twitter_username: thefron
github_username: thefron

# Build settings
markdown: kramdown
highlighter: pygments
github: [Repository metadata]
